development:
  password: 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
  theme_id: "122803322977" # 1.1
  store: beefy-miracle.myshopify.com
  timeout: 30s
  ignore_files:
    - config/settings_data.json
    - locales/
